#!/bin/bash
# Quick Test Reference Card - Apricity Stack

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║          APRICITY STACK - QUICK TEST REFERENCE                 ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "🚀 RUN INTEGRATION TEST"
echo "   ./test-stack.sh"
echo ""
echo "📊 MANUAL API TESTING"
echo ""
echo "1️⃣  Start Services:"
echo "   docker-compose up -d"
echo ""
echo "2️⃣  Check Backend Health:"
echo "   curl http://localhost:5000/health | jq"
echo ""
echo "3️⃣  Check ML Service Health:"
echo "   curl http://localhost:8000/health | jq"
echo ""
echo "4️⃣  Register User:"
echo "   curl -X POST http://localhost:5000/api/auth/register \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"email\":\"test@test.com\",\"password\":\"Pass123!\",\"username\":\"test\"}' | jq"
echo ""
echo "5️⃣  Login:"
echo "   curl -X POST http://localhost:5000/api/auth/login \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"email\":\"test@test.com\",\"password\":\"Pass123!\"}' | jq"
echo ""
echo "6️⃣  Create Diary (save token from step 5):"
echo "   export TOKEN=\"your-jwt-token-here\""
echo "   curl -X POST http://localhost:5000/api/diary \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -H \"Authorization: Bearer \$TOKEN\" \\"
echo "     -d '{\"title\":\"Test\",\"content\":\"I feel anxious today.\"}' | jq"
echo ""
echo "7️⃣  Get Diary with Emotion (save diary ID from step 6):"
echo "   export DIARY_ID=\"your-diary-id-here\""
echo "   curl http://localhost:5000/api/diary/\$DIARY_ID \\"
echo "     -H \"Authorization: Bearer \$TOKEN\" | jq '.data.diary.emotionSummary'"
echo ""
echo "🔍 DEBUGGING"
echo ""
echo "View Logs:"
echo "   docker-compose logs -f backend"
echo "   docker-compose logs -f ml_service"
echo "   docker-compose logs -f mongo"
echo ""
echo "Check Containers:"
echo "   docker-compose ps"
echo ""
echo "Restart Services:"
echo "   docker-compose restart"
echo ""
echo "Clean Restart:"
echo "   docker-compose down -v && docker-compose up -d"
echo ""
echo "🧹 CLEANUP"
echo ""
echo "Stop Services:"
echo "   docker-compose down"
echo ""
echo "Remove Volumes:"
echo "   docker-compose down -v"
echo ""
echo "Remove Everything:"
echo "   docker-compose down -v --rmi all"
echo ""
echo "📝 TEST DIARY CONTENT EXAMPLES"
echo ""
echo "Happy:   'I had an amazing day! Everything went perfectly!'"
echo "Sad:     'I feel really down and lonely today.'"
echo "Anxious: 'I am so worried about my upcoming presentation.'"
echo "Angry:   'I am so frustrated and angry about what happened!'"
echo "Neutral: 'I went to the store and bought some groceries.'"
echo ""
echo "⚡ QUICK COMMANDS"
echo ""
echo "Full stack with frontend:"
echo "   docker-compose --profile full up -d"
echo ""
echo "Run tests and cleanup:"
echo "   ./test-stack.sh && docker-compose down"
echo ""
echo "Watch backend logs during test:"
echo "   docker-compose logs -f backend &"
echo "   ./test-stack.sh"
echo ""
